enableGlobalCache: false

pnpEnableEsmLoader: true

packageExtensions:
  '@bufbuild/connect-node@*':
    peerDependencies:
      '@bufbuild/connect': '0.13'
  '@wolfcoded/nestjs-bufconnect@*':
    peerDependencies:
      '@bufbuild/connect-node': '0.13'
      '@bufbuild/connect': '0.13'
  '@monstrs/nestjs-buf-errors@*':
    peerDependencies:
      '@bufbuild/connect': '0.13'
  '@mikro-orm/knex@*':
    dependencies:
      '@mikro-orm/entity-generator': '*'
      '@mikro-orm/migrations': '*'
  '@mikro-orm/postgresql@*':
    dependencies:
      '@mikro-orm/core': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      ioredis: '*'
      kafkajs: '*'
  testcontainers@*:
    dependencies:
      '@types/dockerode': '*'
  knex@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      tedious: '*'

yarnPath: .yarn/releases/yarn-remote.cjs
